# Generated by Django 3.2.8 on 2021-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='fe1f179f-a663-4ad3-b0dd-5cb0486aeef4', editable=False),
        ),
    ]
