# Generated by Django 3.2.8 on 2021-11-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_account_uuid_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='9b83693d-0c48-4ab0-8d9a-ec7c714242cc', editable=False),
        ),
    ]
