# Generated by Django 3.2.8 on 2021-11-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Change_Amount', models.IntegerField()),
                ('Meesege', models.CharField(blank=True, max_length=500)),
                ('is_Approved', models.BooleanField(default=False)),
                ('Project_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkout.project_creation')),
            ],
        ),
    ]
