# Generated by Django 3.2.8 on 2021-11-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earned_by_Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Money_Reciever', models.IntegerField()),
                ('Money_Releser', models.IntegerField()),
                ('Value', models.IntegerField(blank=True, default=0)),
                ('Date_Created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proof_Url', models.URLField()),
                ('Proof_Url_Scnd', models.URLField(blank=True)),
                ('Proof_Url_Third', models.URLField(blank=True)),
                ('Messege', models.CharField(blank=True, default='N/A', max_length=500)),
                ('Project_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkout.project_creation')),
            ],
        ),
    ]
